# https://packaging.python.org/ja/latest/guides/writing-pyproject-toml/
[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paper-manager"
dynamic = ["version"]
dependencies = [
    "crossrefapi == 1.6.0",
    # "crossrefapi @ git+https://github.com/fabiobatalha/crossrefapi.git@1.6.1",
    "pandas",
    "streamlit >=1.38.0",
    "bibtexparser",
    "streamlit-pdf-viewer",
    "pybtex",
    "bib2xml @ git+https://github.com/yu9824/bib2xml.git@v0.1.5",
]
requires-python = ">= 3.9"
authors = [{ name = "yu9824" }]
maintainers = [{ name = "yu9824" }]
description = ""
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["paper-manager"]
# https://pypi.org/classifiers/
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
] # https://pypi.org/classifiers/

[project.optional-dependencies]
test = ["pytest"]
dev = ["build"]
optional = ["colorlog", "tqdm"]
docs = [
    "sphinx",
    "myst-parser",
    "myst-nb",
    "sphinx-book-theme",
    "jupyter-sphinx",
]

[project.urls]
Homepage = "https://github.com/yu9824/paper-manager"
# Documentation = "https://readthedocs.org"
# PyPI = "https://pypi.org/project/paper-manager/"
Source = "https://github.com/yu9824/paper-manager"
Tracker = "https://github.com/yu9824/paper-manager/issues"
Changelog = "https://github.com/yu9824/paper-manager/blob/main/CHANGELOG.md"

[project.scripts]
paper-manager = "paper_manager.__main__:entrypoint"

# [project.gui-scripts]
# paper-manager = "paper_manager.__main__:entrypoint"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.dynamic]
version = { attr = "paper_manager.__version__" }

[tool.setuptools.packages.find]
where = ["src/"]

[tool.setuptools.package-data]
"paper_manager.app" = ["fields.json"]

[tool.ruff]
line-length = 79
indent-width = 4

[tool.ruff.lint]
unfixable = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
