import os
from pathlib import Path

__all__ = (
    "AUTHOR_SEPARATOR",
    "TAG_SEPARATOR",
    "DIRPATH_ROOT",
    "DIRPATH_APP",
    "DIRPATH_DATA",
    "DIRPATH_PDF",
    "FILEPATH_LIST",
    "FILEPATH_FIELDS",
    "COLNAME_HAS_PDF",
    "COLNAME_YEAR",
    "COLNAME_AUTHOR",
    "COLNAME_TITLE",
    "COLNAME_JOURNAL",
    "COLNAME_VOLUME",
    "COLNAME_NUMBER",
    "COLNAME_PAGES",
    "COLNAME_DOI",
    "COLNAME_TAGS",
    "COLNAMES_DISPLAY",
    "ENCODING",
)


AUTHOR_SEPARATOR = " and "
TAG_SEPARATOR = ", "

DIRPATH_ROOT = Path(__file__).parent

DIRPATH_APP = DIRPATH_ROOT / "app"
_data_dir = os.environ.get("PAPER_MANAGER_DATA_DIR")
if _data_dir:
    DIRPATH_DATA = Path(_data_dir).expanduser()
else:
    DIRPATH_DATA = Path.home() / ".paper-manager"


DIRPATH_PDF = DIRPATH_DATA / "pdf"
FILEPATH_LIST = DIRPATH_DATA / "list.json"
FILEPATH_FIELDS = DIRPATH_APP / "fields.json"

COLNAME_HAS_PDF = "PDF"
COLNAME_YEAR = "year"
COLNAME_AUTHOR = "author"
COLNAME_TITLE = "title"
COLNAME_JOURNAL = "journal"
COLNAME_VOLUME = "volume"
COLNAME_NUMBER = "number"
COLNAME_PAGES = "pages"
COLNAME_DOI = "DOI"
COLNAME_TAGS = "tags"
COLNAMES_DISPLAY = (
    COLNAME_HAS_PDF,
    COLNAME_YEAR,
    COLNAME_AUTHOR,
    COLNAME_TITLE,
    COLNAME_JOURNAL,
    COLNAME_VOLUME,
    COLNAME_NUMBER,
    COLNAME_PAGES,
    COLNAME_DOI,
    COLNAME_TAGS,
)

ENCODING = "utf-8"
